#!/usr/bin/env python3
"""render-motif-pack.py — turn a VALIDATED motif pack (one JSON file) into
one deterministic <style> head-injection block + head assets (design-system
unification spec §2.2/§2.3, WP-4). ZERO repo CSS is touched: the pack's
entire visual effect ships as generated per-issue head markup.

Modes:
  python3 tools/motif/render-motif-pack.py PACK.json
      Canonical head block to stdout (goldenized form).
  ... PACK.json --out FILE
      Canonical head block to FILE.
  ... PACK.json --inject TARGET.html --out OUT.html
      Re-theme a data-mx page: writes a copy of TARGET with the pack block
      injected at the marker `<!-- INJECT:MX-PACK -->` (or immediately
      before </head> when the marker is absent — i.e. after the bundle and
      any per-issue styles, so pack tokens win the cascade), page act names
      aliased onto pack acts, `mx-ground-pattern--has-art` stamped where a
      pattern ships, a corner glyph watermark per act section (the layer-33
      mechanism generalized: currentColor via the core .mx-glyph mask slot),
      and body data-motion set to the pack's tier.
  ... PACK.json --check-golden
      Diff canonical output against tools/motif/golden/<id>.golden.html;
      exit 1 on drift (CI determinism proof).
  ... PACK.json --write-golden
      (Re)write the golden copy. Requires a PROGRESS-recorded decision.

What the generated block contains:
  - @font-face for self-hosted whitelist families the pack uses (files under
    assets/fonts/ only — a pack can never introduce a network font)
  - body-level defaults on [data-mx] (act 1 tokens + six type-role remaps +
    grain + art slots)
  - per-act token blocks scoped section[data-act="N"] / [data-act="N"]
  - --mx-pattern per act as a data-URI with currentColor resolved to the
    act's ink (SVG-as-background cannot inherit currentColor; the pack
    knows each act's ink, so it is resolved at generation time)
  - --mx-glyph as a data-URI left on currentColor (mask-image uses the
    alpha channel; the core .mx-glyph slot paints background: currentColor)
  - --mx-band as a data-URI + a consumption rule on .mx-transit
  - <template data-mx-pack-cover-plate> when the pack carries a cover plate

Exit 0 success · 1 validation rejection, golden drift, or injection failure.
stdlib only; deterministic output (no timestamps).
"""

import hashlib
import re
import sys
import urllib.parse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from motiflib import (  # noqa: E402
    GRAINS, INJECT_MARKER, MOTIF_DIR, TYPE_ROLES,
    load_whitelist, validate_pack,
)

GOLDEN_DIR = MOTIF_DIR / "golden"

GENERIC_FAMILIES = {"serif", "sans-serif", "cursive", "monospace",
                    "ui-monospace", "system-ui"}


def css_family(name: str) -> str:
    return name if name in GENERIC_FAMILIES else f'"{name}"'


def font_stack(family: str, families: dict) -> str:
    fallback = families[family].get("fallback", [])
    return ", ".join(css_family(f) for f in [family] + list(fallback))


def minify_svg(svg: str) -> str:
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    svg = re.sub(r"\s+", " ", svg).strip()
    svg = re.sub(r">\s+<", "><", svg)
    return svg


def svg_data_uri(svg: str, current_color: str | None = None) -> str:
    """Deterministic utf8 data-URI. current_color, when given, resolves
    currentColor at generation time (background-image SVGs cannot inherit
    it from the embedding element)."""
    src = minify_svg(svg)
    if current_color:
        src = src.replace("currentColor", current_color)
    encoded = urllib.parse.quote(src, safe="-_.~!*'();:@=+$,/?")
    return f'url("data:image/svg+xml;utf8,{encoded}")'


def act_decls(act: dict, pattern_svg: str | None, indent: str = "  ") -> str:
    lines = []
    for key, value in act["tokens"].items():
        lines.append(f"{indent}{key}: {value};")
    if pattern_svg is not None:
        ink = act["tokens"].get("--mx-ink", "#000")
        lines.append(f"{indent}--mx-pattern: {svg_data_uri(pattern_svg, current_color=ink)};")
    return "\n".join(lines)


def render_head(pack: dict, art: dict, families: dict, pack_bytes: bytes,
                alias_map: dict | None = None) -> str:
    """alias_map: page-act-name -> pack act id (inject mode only; the
    canonical/golden form has no aliases)."""
    pid = pack["id"]
    digest = hashlib.sha256(pack_bytes).hexdigest()[:12]
    acts = pack["acts"]
    typ = pack["type"]
    out = []
    out.append(f"<!-- mx-pack:begin id={pid} sha256={digest} "
               f"kit={pack['kit']} motion={pack['motion']} -->")
    out.append(f'<style data-mx-pack="{pid}">')
    out.append(f"/* generated by tools/motif/render-motif-pack.py from {pid}.json — do not hand-edit.")
    out.append("   L2 motif pack: per-issue tokens + art; never repo CSS (spec §2.1). */")

    # -- @font-face for self-hosted whitelist families the pack uses ----
    used = sorted({typ[r] for r in TYPE_ROLES})
    for fam in used:
        meta = families[fam]
        if meta.get("kind") != "self-hosted":
            continue
        for face in meta["faces"]:
            out.append("@font-face {")
            out.append(f'  font-family: "{fam}";')
            out.append(f'  src: url("/assets/fonts/{face["file"]}") format("woff2");')
            out.append(f"  font-weight: {face['weight']}; font-style: {face['style']}; font-display: swap;")
            out.append("}")

    # -- body-level defaults: act 1 + type + grain + art slots ----------
    grain = GRAINS[pack["grain"]]
    out.append("[data-mx] {")
    out.append(act_decls(acts[0], art["pattern"]))
    for role in TYPE_ROLES:
        out.append(f"  --mx-t-{role}: {font_stack(typ[role], families)};")
    if "--mx-grain" not in acts[0]["tokens"]:
        out.append(f"  --mx-grain: {grain};")
    if art["glyph"] is not None:
        out.append(f"  --mx-glyph: {svg_data_uri(art['glyph'])};")
    if art["band"] is not None:
        out.append(f"  --mx-band: {svg_data_uri(art['band'])};")
    out.append("}")

    # -- per-act token blocks scoped section[data-act="N"] --------------
    def emit_act_block(selector_key: str, act: dict):
        out.append(f'[data-mx] section[data-act="{selector_key}"],')
        out.append(f'[data-mx] [data-act="{selector_key}"] {{')
        out.append(act_decls(act, art["pattern"]))
        if "--mx-grain" not in act["tokens"]:
            out.append(f"  --mx-grain: {grain};")
        out.append("}")

    for act in acts:
        emit_act_block(str(act["id"]), act)

    if alias_map:
        out.append("/* act aliases — this page's data-act names mapped onto pack acts */")
        by_id = {a["id"]: a for a in acts}
        for page_name, act_id in alias_map.items():
            if page_name in {str(a["id"]) for a in acts} or \
               page_name in {a.get("name") for a in acts if str(a["id"]) == page_name}:
                continue
            emit_act_block(page_name, by_id[act_id])

    # also scope by the pack's own act names (packs address acts by name in
    # authored issues: section data-act="night" etc.)
    for act in acts:
        name = act.get("name")
        if name and name != str(act["id"]) and not (alias_map and name in alias_map):
            emit_act_block(name, act)

    # -- art consumption rules (pack-generated, never repo CSS) ---------
    if art["glyph"] is not None:
        out.append("/* corner glyph watermark — layer-33 mechanism generalized:")
        out.append("   .mx-glyph (core 13-chrome) masks --mx-glyph over background:")
        out.append("   currentColor, so the mark always rides the act's ink. */")
        out.append("[data-mx] .mx-pack-glyph-corner {")
        out.append("  position: absolute;")
        out.append("  right: clamp(16px, 3vw, 48px);")
        out.append("  bottom: clamp(16px, 3vw, 48px);")
        out.append("  width: clamp(80px, 12vw, 180px);")
        out.append("  height: clamp(80px, 12vw, 180px);")
        out.append("  opacity: 0.07;")
        out.append("  z-index: 1;              /* above grounds, below .mx-wrap (z2) */")
        out.append("  pointer-events: none;")
        out.append("}")
    if art["band"] is not None:
        out.append("/* band slot — decorative strip pinned to the transit seam */")
        out.append("[data-mx] .mx-transit {")
        out.append("  background-image: var(--mx-band);")
        out.append("  background-size: auto 26px;")
        out.append("  background-repeat: repeat-x;")
        out.append("  background-position: center bottom 12px;")
        out.append("}")
    out.append("</style>")

    if art["cover_plate"] is not None:
        out.append(f'<template data-mx-pack-cover-plate="{pid}">')
        out.append(minify_svg(art["cover_plate"]))
        out.append("</template>")
    out.append(f"<!-- mx-pack:end id={pid} -->")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- inject

def build_alias_map(body_html: str, pack: dict) -> dict:
    """Distinct page data-act names in document order -> pack act ids.
    Name-identical acts map directly; the rest are assigned in order,
    cycling through the pack's acts."""
    page_acts = []
    for m in re.finditer(r'data-act="([^"]+)"', body_html):
        if m.group(1) not in page_acts:
            page_acts.append(m.group(1))
    by_name = {a.get("name"): a["id"] for a in pack["acts"]}
    ids = [a["id"] for a in pack["acts"]]
    alias, cursor = {}, 0
    for name in page_acts:
        if name in by_name:
            alias[name] = by_name[name]
        elif name in {str(i) for i in ids}:
            continue  # already scoped canonically
        else:
            alias[name] = ids[cursor % len(ids)]
            cursor += 1
    return alias


def inject(pack: dict, art: dict, families: dict, pack_bytes: bytes,
           target: Path, out: Path) -> list[str]:
    html = target.read_text(encoding="utf-8")
    notes = []
    head_end = re.search(r"</head\s*>", html, re.I)
    if not head_end:
        print("ERROR: target has no </head> — cannot inject", file=sys.stderr)
        raise SystemExit(1)
    body_html = html[head_end.end():]

    alias_map = build_alias_map(body_html, pack)
    block = render_head(pack, art, families, pack_bytes, alias_map=alias_map)

    if INJECT_MARKER in html:
        html = html.replace(INJECT_MARKER, block, 1)
        notes.append(f"injected at marker {INJECT_MARKER}")
    else:
        html = html[:head_end.start()] + block + html[head_end.start():]
        notes.append("no marker — injected immediately before </head>")
    if alias_map:
        notes.append("act aliases: " + ", ".join(f"{k}->act{v}" for k, v in alias_map.items()))

    # pattern art: opt the ground elements into art opacity (core contract:
    # add mx-ground-pattern--has-art when a pack supplies art)
    if art["pattern"] is not None:
        def add_art_class(m):
            cls = m.group(1)
            if "mx-ground-pattern--has-art" in cls or "mx-ground-pattern" not in cls:
                return m.group(0)
            return m.group(0).replace(cls, cls + " mx-ground-pattern--has-art", 1)
        new_html, n = re.subn(r'class="([^"]*)"', add_art_class, html)
        stamped = new_html.count("mx-ground-pattern--has-art") - html.count("mx-ground-pattern--has-art")
        html = new_html
        notes.append(f"pattern art: stamped mx-ground-pattern--has-art on {stamped} element(s)")

    # glyph art: one corner watermark per act section (the layer-33 gesture)
    if art["glyph"] is not None:
        span = '\n<span class="mx-glyph mx-pack-glyph-corner" aria-hidden="true"></span>'
        head_end2 = re.search(r"</head\s*>", html, re.I)
        head_part, body_part = html[:head_end2.end()], html[head_end2.end():]
        body_part, n = re.subn(r'(<section\b[^>]*\bdata-act="[^"]+"[^>]*>)',
                               r"\1" + span, body_part)
        html = head_part + body_part
        notes.append(f"glyph: corner watermark span added to {n} act section(s)")

    # motion: the pack declares the tier
    tier = pack["motion"]
    head_end3 = re.search(r"</head\s*>", html, re.I)
    body_tag = re.search(r"<body\b[^>]*>", html[head_end3.end():], re.I)
    if body_tag:
        tag = body_tag.group(0)
        if 'data-motion="' in tag:
            new_tag = re.sub(r'data-motion="[^"]*"', f'data-motion="{tier}"', tag)
        else:
            new_tag = tag[:-1] + f' data-motion="{tier}">'
        if new_tag != tag:
            s = head_end3.end() + body_tag.start()
            e = head_end3.end() + body_tag.end()
            html = html[:s] + new_tag + html[e:]
        notes.append(f'body data-motion="{tier}"')

    out.write_text(html, encoding="utf-8")
    return notes


# ---------------------------------------------------------------- main

def main(argv):
    args = argv[1:]
    pack_path = None
    out_path = None
    inject_target = None
    whitelist = None
    mode = "render"
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--out":
            out_path = Path(args[i + 1]); i += 2
        elif a == "--inject":
            inject_target = Path(args[i + 1]); mode = "inject"; i += 2
        elif a == "--check-golden":
            mode = "check-golden"; i += 1
        elif a == "--write-golden":
            mode = "write-golden"; i += 1
        elif a == "--whitelist":
            whitelist = Path(args[i + 1]); i += 2
        elif a.startswith("--"):
            print(f"unknown flag {a}\n{__doc__}", file=sys.stderr); return 2
        else:
            pack_path = Path(a); i += 1
    if pack_path is None:
        print(__doc__); return 2

    # a pack renders ONLY if it validates green (same rules as the validator)
    pack, art, report, errors = validate_pack(pack_path, whitelist)
    if errors:
        print(f"REFUSING TO RENDER — pack failed validation ({pack_path}):", file=sys.stderr)
        for e in errors:
            print(f"  REJECT [{e.code}] {e}", file=sys.stderr)
        return 1

    families = load_whitelist(whitelist)
    pack_bytes = pack_path.read_bytes()

    if mode == "inject":
        if out_path is None:
            print("--inject requires --out OUT.html", file=sys.stderr); return 2
        notes = inject(pack, art, families, pack_bytes, inject_target, out_path)
        print(f"INJECTED pack {pack['id']} -> {out_path}")
        for n in notes:
            print(f"  {n}")
        return 0

    canonical = render_head(pack, art, families, pack_bytes)
    golden = GOLDEN_DIR / f"{pack['id']}.golden.html"

    if mode == "write-golden":
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden.write_text(canonical, encoding="utf-8")
        print(f"GOLDEN WRITTEN: {golden} ({len(canonical.encode())} bytes)")
        return 0
    if mode == "check-golden":
        if not golden.is_file():
            print(f"GOLDEN MISSING: {golden}", file=sys.stderr)
            return 1
        want = golden.read_text(encoding="utf-8")
        if want == canonical:
            print(f"GOLDEN OK: {pack['id']} — current output is byte-identical to {golden.name}")
            return 0
        import difflib
        diff = list(difflib.unified_diff(want.splitlines(), canonical.splitlines(),
                                         fromfile=str(golden), tofile="current", lineterm=""))
        print(f"GOLDEN DRIFT: {pack['id']} — output differs from {golden.name}:", file=sys.stderr)
        for line in diff[:40]:
            print(f"  {line}", file=sys.stderr)
        if len(diff) > 40:
            print(f"  ... {len(diff) - 40} more diff line(s)", file=sys.stderr)
        return 1

    if out_path:
        out_path.write_text(canonical, encoding="utf-8")
        print(f"WROTE {out_path} ({len(canonical.encode())} bytes)")
    else:
        sys.stdout.write(canonical)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
